<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>4f7acffe-1e9e-4308-ae56-8e9421a8531d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="9.4.2" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="9.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenLibraryRent\OpenLibraryRent.csproj" />
  </ItemGroup>

</Project>
